// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Data.Migrations
{
    [DbContext(typeof(RomDbContext))]
    partial class RomDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("API.Entities.DefectiveComponentDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ComponentName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ComponentType")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DefectiveComponentDetail");
                });

            modelBuilder.Entity("API.Entities.ProcessRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ComponentDetailId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComponentDetailId");

                    b.ToTable("ProcessRequests");
                });

            modelBuilder.Entity("API.Entities.ProcessRequest", b =>
                {
                    b.HasOne("API.Entities.DefectiveComponentDetail", "ComponentDetail")
                        .WithMany()
                        .HasForeignKey("ComponentDetailId");

                    b.Navigation("ComponentDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
